version: '3.1'

services:
  springboot:
    build:
      dockerfile: Dockerfile
      context: .
    image: springboot:latest
    restart: unless-stopped
    container_name: task-application
    env_file:
      - ./server-config.env
    ports:
      - 8082:8088
    expose:
      - 8082
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: task-mongo
    ports:
      - 27017:27017
    restart: unless-stopped
    command: mongod

  mongo-seed:
    image: mongo:latest
    container_name: mongo_seed
    links:
      - mongodb
    volumes:
      - ./.docker/mongo-settings:/mongo-settings
    command:
      /mongo-settings/migrate.sh
